services:
  mongodb:
    image: mongo:latest
    container_name: validation_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: validation_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb

volumes:
  mongo_data:
    driver: local
